= Midas Loop
:author: Luke Gessler, Lauren Levine, Amir Zeldes
:lang: en
:encoding: UTF-8
:doctype: book
:toc: left
:toclevels: 3
:sectlinks:
:sectanchors:
:leveloffset: 1
:sectnums:
:imagesdir: img/src
:imagesoutdir: img/out
:favicon: favicon.ico
:hide-uri-scheme: 1

= Introduction


= Development
https://leiningen.org/[Leiningen] is used to build code.

== Dev Server
Run `lein repl` in order to get a dev REPL, then execute `(start)` in the prompt.
`(stop)` and `(restart)` are also available in the REPL.
This will use the config at `env/dev/resources/config.edn`.

== Testing
Run `lein test`.
This will use the config at `env/test/resources/config.edn`.

== Prod Build
Run `lein uberjar`.
This will produce a standalone JAR ready for distribution and execution via `java -jar`.
Unless overridden, this will use the config at `env/prod/resources/config.edn`.

== Building Docs
Install https://docs.asciidoctor.org/asciidoctor/latest/install/[Asciidoctor], then:

```
asciidoctor-pdf -o target/book.pdf -b pdf -r asciidoctor-diagram docs/book.adoc
asciidoctor -o target/book.html -b html -r asciidoctor-diagram docs/book.adoc
```

= Setup
== Server
Get an uberjar (cf. <<Prod Build>>).
Note the following top level commands:

```
COMMANDS:
run, r               Start the web app and begin listening for requests.
import, i            Read and ingest CoNLL-U files.
export, e            Export all documents in the database as CoNLL-U files.
token, t             Token-related helpers.
```

Run one of the top level commands (e.g. `java -jar midas-loop.jar import --help`) to see more details about each command.

IMPORTANT: Each command requires that your server not be running.
If you are running your server using the `run` command, be sure you shut it down before running any of the other commands.

== Authorization
=== Granting
Token-based authorization is used.
Each user should have a token made for them, like so:

```
java -jar midas-loop.jar token add --name "Sam Doe" --email "sd42@gmail.com" --quality "gold"
```

Give your user their token and instruct them to keep it secret.

NOTE: Tokens that will be used by humans should have `gold` quality, and tokens that will be used by models should have `silver` quality.

=== Listing
You can see all valid tokens with `java -jar midas-loop.jar token list`.

=== Revoking
You can revoke a token like so:

```
java -jar midas-loop.jar token revoke --secret "gold;secret=84EO60tU6lhcBhplbuEEGElECuh1yZod8fTCn6DqkQA"
```

== NLP Services
Midas Loop is able to contact _NLP services_ via HTTP in order to get machine learning model outputs for certain kinds of annotations.
NLP services work by waiting to be contacted by the Midas Loop server, which will contact the service when it needs fresh label distributions for a given annotation type.

Specifically, Midas Loop is able to accommodate outputs for sentence splits (i.e., token-level classification of whether a particular token is the beginning of a new sentence) as well as UPOS, XPOS, and HEAD annotations.
For each of these annotation types, it is expected that a service will be able to take a sentence as input and provide a list of _probability distribution_ over labels, one distribution per token.

=== Inputs
The service should be listening for POST requests at `/`, and can expect that the JSON payload will include the keys `conllu` and `json`: the `conllu` key will have the stringified CoNLL-U representation of the sentence, and the `json` key will have Midas Loop's verbose internal representation of the sentence.

=== Outputs
The service should respond with a JSON in the response body with a single key, `probabilities`.
The value associated with this key should be a list of objects (= Python dicts) where each object holds key-value pairs expressing labels' probabilities as predicted by the model for the corresponding token at that position.
Values should sum to 1.

For any input sentence, the number of output label distributions must *exactly* match the expected numbers.
For UPOS, XPOS, and HEAD, this is the number of normal tokens or ellipsis tokens, and for sentence splits, this is the number of normal tokens.
Model outputs will be rejected if the expected number of label distributions is not met.

Note that for HEAD, values *must* be the internal IDs for tokens provided in the `json` input representation, i.e. UUIDs such as `013769d9-dc90-4278-9bc2-5d6a9f96d0fc` instead of CoNLL-U IDs like `3` or `11.2`.

WARNING: Be sure that you are using the ID for the *token* entity in the JSON, and not the *head* entity in the JSON, when providing your outputs.

=== Service Registration
NLP services will not be contacted unless Midas Loop is told about them. See `:nlp-services` in <<Configuration>>.

=== Example

Consider a sample XPOS tagging service at https://github.com/gucorpling/midas-loop/blob/master/services/sample_xpos.py[`services/sample_xpos.py`].
This is a barebones HTTP service implemented using Flask which loads a pretrained English part of speech tagger from spaCy and uses it to respond to requests.
It listens for a POST request, and when it receives it, uses the model to parse the CoNLL-U string and recover the probabilities from the model's outputs.
Note that the model is initialized globally so that it may reside in memory in between requests.

== Configuration
By default, the uberjar will use its copy of the config located at https://github.com/lgessler/midas-loop/blob/master/env/prod/resources/config.edn[`env/prod/resources/config.edn`].
If you wish to customize this, specify another config using `-Dconf=...`:

`java -Dconf="/path/to/my/config.edn" -jar midas-loop.jar ...`

Config keys:

[cols="1,1"]
|===
|`:midas-loop.server.xtdb/config`
|Should be a map with two subkeys: `:main-db-dir` (required) has a string specifying the main database's path on the filesystem relative to the CWD; `:http-server-port`, if present, should be a number specifying the port on which to serve XTDB's internal HTTP interface.

|`:midas-loop.server.tokens/config`
|Map with a single key, `:token-db-dir`, (required) which specifies the location on the filepath of the authorization token database.

|`:dev`
|Either `true` or `false`. If `true`, do not require any authorization. This should always be `false` in production.

|`:nlp-services`
| A vector of three-key maps. Each map should have a `:type` (currently always `:http`), a `:anno-type` (must be `:sentence`, `:xpos`, `:upos`, or `:head`), and a url (must be pointed at running <<NLP Services>>)

|`:nlp-retry-wait-period-ms`
| Time, in milliseconds, to wait after a failure before attempting to contact an HTTP NLP service again. Defaults to `10000` (10 seconds).

|`:port`
| Port used for the main web server.

| `:cors-patterns`
| A set of CORS patterns (regular expressions) for adding additional allowed origins, e.g. `#{"*.georgetown.edu"}`.
Localhost and the main origin are always allowed regardless of this item's value.
|===

= Operation
== Importing
`java -jar midas-loop.jar import dir/with/conllu-files/`

== API
Run your server and see `/swagger-ui/`.

TODO: add detail

=== Upload
=== Diffing
